.deploy: &deploy
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version
    - apk add --no-cache --update alpine-sdk # git make gcc ...
    - bundle install --clean --deployment --jobs=2 --without default development lint production test
  image: ruby:alpine
  only:
    - master
  stage: deploy
  tags:
    - ruby

.lint: &lint
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version
    - apk add --no-cache --update git
    - bundle install --clean --deployment --jobs=2 --without default deployment development production test
  image: ruby:alpine
  stage: lint
  tags:
    - ruby

.test: &test
  artifacts:
    expire_in: 1 day
    paths:
      - coverage
  script:
    - bundle install --clean --deployment --jobs=$(nproc) --without deployment development lint production
    - bin/rake
  stage: test
  tags:
    - ruby

.use_jruby: &use_jruby
  <<: *test
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version
    - apt-get -qq update
    - apt-get -qq install git
  image: jruby:9.1

.use_mri: &use_mri
  <<: *test
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version

.use_rails_4_0_x: &use_rails_4_0_x
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-4.0.x

.use_rails_4_1_x: &use_rails_4_1_x
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-4.1.x

.use_rails_4_2_x: &use_rails_4_2_x
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-4.2.x

.use_rails_5_0_x: &use_rails_5_0_x
  variables:
    BUNDLE_GEMFILE: Gemfile

cache:
  paths:
    - vendor/bundle

lint:brakeman:
  <<: *lint
  artifacts:
    expire_in: 1 day
    paths:
      - brakeman
    when: always
  script:
    - bin/brakeman --exit-on-warn --output brakeman/index.html

lint:bundler:audit:
  <<: *lint
  script:
    - bin/bundle-audit check --update --verbose

lint:rubocop:
  <<: *lint
  script:
    - bin/rubocop

pages:
  <<: *deploy
  artifacts:
    expire_in: 1 month
    paths:
      - public
  script:
    - bin/codeclimate-test-reporter
    - DIR=public/$([ "$CI_COMMIT_REF_SLUG" = master ] || echo $CI_COMMIT_REF_SLUG)
    - mkdir -pv $DIR
    - mv -v brakeman $DIR
    - mv -v coverage $DIR
  except:
    - tags

stages:
  - lint
  - test
  - deploy

test:rails-4.0.x:jruby:9.1:
  <<: *use_jruby
  <<: *use_rails_4_0_x

test:rails-4.0.x:mri:2.2:
  <<: *use_mri
  <<: *use_rails_4_0_x
  image: ruby:2.2

test:rails-4.0.x:mri:2.3:
  <<: *use_mri
  <<: *use_rails_4_0_x
  image: ruby:2.3

test:rails-4.1.x:jruby:9.1:
  <<: *use_jruby
  <<: *use_rails_4_1_x

test:rails-4.1.x:mri:2.2:
  <<: *use_mri
  <<: *use_rails_4_1_x
  image: ruby:2.2

test:rails-4.1.x:mri:2.3:
  <<: *use_mri
  <<: *use_rails_4_1_x
  image: ruby:2.3

test:rails-4.2.x:jruby:9.1:
  <<: *use_jruby
  <<: *use_rails_4_2_x

test:rails-4.2.x:mri:2.2:
  <<: *use_mri
  <<: *use_rails_4_2_x
  image: ruby:2.2

test:rails-4.2.x:mri:2.3:
  <<: *use_mri
  <<: *use_rails_4_2_x
  image: ruby:2.3

test:rails-4.2.x:mri:2.4:
  <<: *use_mri
  <<: *use_rails_4_2_x
  image: ruby:2.4

test:rails-5.0.x:jruby:9.1:
  <<: *use_jruby
  <<: *use_rails_5_0_x

test:rails-5.0.x:mri:2.2:
  <<: *use_mri
  <<: *use_rails_5_0_x
  image: ruby:2.2

test:rails-5.0.x:mri:2.3:
  <<: *use_mri
  <<: *use_rails_5_0_x
  image: ruby:2.3

test:rails-5.0.x:mri:2.4:
  <<: *use_mri
  <<: *use_rails_5_0_x
  image: ruby:2.4

variables:
  JRUBY_OPTS: --debug
  LC_ALL: C.UTF-8
  RAILS_ENV: test
